import type { Msg } from './common.js'
export const pages = {
  // ---- history / activity
  // ---- tabs
  // ---- shared ui
  // ---- AI command center / timeline
  // ---- analysis center
  // ---- ownership page
  // ---- nominee page
  // ---- employment
  // ---- contract
  // ---- language & culture
  'lng.title': ['ภาษาและวัฒนธรรมทางธุรกิจ', '语言与商务文化', 'Language and business culture'],
  'lng.sub': ['ศัพท์กฎหมายไม่ควรแปลตรงตัว ระบบจึงแสดงคำอธิบาย ศัพท์ต้นฉบับ และบริบทควบคู่กัน', '法律术语不宜直译，因此系统同时给出说明、原文术语和语境。', 'Legal terms should not be translated word for word, so the system shows the explanation, the original term and the context together.'],
  'lng.table': ['ตารางศัพท์ · ต้นฉบับ · ความหมาย/บริบท', '术语表 · 原文 · 含义/语境', 'Glossary · original · meaning/context'],
  'lng.col1': ['คำอธิบาย (ภาษาที่เลือก)', '说明（所选语言）', 'Explanation (selected language)'],
  'lng.col2': ['ศัพท์ต้นฉบับ', '原文术语', 'Original term'],
  'lng.col3': ['ความหมาย/บริบท', '含义/语境', 'Meaning / context'],
  'lng.note': ['ภาษาที่รองรับ: ไทย · จีน · อังกฤษ (ตัวอย่างคำศัพท์สำหรับ Prototype)', '支持语言：泰语 · 中文 · 英语（原型示例术语）', 'Supported languages: Thai · Chinese · English (sample terms for the prototype)'],
  'cul.title': ['แนวโน้มที่ควรคำนึงถึง ตามสถานการณ์ของคุณ', '根据您的情境，值得留意的倾向', 'Tendencies worth considering, by situation'],
  'cul.warn': ['ข้อมูลนี้เป็นเพียง “แนวโน้มที่ควรคำนึงถึง” ไม่ใช่ข้อสรุปเกี่ยวกับบุคคลหรือคนทั้งกลุ่ม ทุกองค์กรและทุกคนมีความแตกต่างกัน ควรสอบถามและปรับตามสถานการณ์จริง', '以下只是“值得留意的倾向”，并非对个人或整个群体的结论。每个组织和每个人都不同，请根据实际情况询问并调整。', 'These are only tendencies worth considering, not conclusions about individuals or whole groups. Every organisation and person differs — ask and adapt to the real situation.'],
  'cul.pick': ['เลือกสถานการณ์', '选择情境', 'Choose a situation'],
  // ---- dashboard
  // ---- risk board
  // ---- roadmap
  // ---- documents
  // ---- monitoring
  // ---- sources / admin
  'src.title': ['ศูนย์แหล่งข้อมูล', '信息来源中心', 'Source centre'],
  'src.sub': ['ทุกข้อกำหนดที่ระบบแสดงต้องอ้างอิงแหล่งทางการ กรุณากดลิงก์เพื่อตรวจสอบฉบับจริงเสมอ', '系统展示的每项规定都须引用官方来源，请务必点击链接核对正式文本。', 'Every requirement shown must cite an official source — always follow the link to check the real text.'],
  'src.warn': ['ข้อมูลตัวอย่างสำหรับ Prototype: ระเบียนด้านล่างเป็นการสรุปแบบย่อเพื่อสาธิตโครงสร้างข้อมูล ไม่ใช่ข้อมูลกฎหมายแบบเรียลไทม์ ลิงก์ชี้ไปยังหน้าหลักของหน่วยงาน และยังไม่มีระเบียนใดผ่านการตรวจสอบโดยผู้เชี่ยวชาญ (สถานะจึงเป็น “ต้องให้ผู้เชี่ยวชาญตรวจ”)', '原型示例数据：以下记录是为演示数据结构而作的简要概述，并非实时法规数据；链接指向机构首页，且尚无任何记录经专家核查（因此状态为“需专家审核”）。', 'Prototype sample data: the records below are short summaries to demonstrate the data structure, not real-time law; links point to agency home pages and no record has been expert-reviewed (hence “expert review required”).'],
  'src.search': ['ค้นหาแหล่งข้อมูล/หัวข้อ', '搜索来源/主题', 'Search sources/topics'],
  'src.allCountries': ['ทุกประเทศ', '所有国家', 'All countries'],
  // ---- pricing / privacy
  'pri.title': ['ความเป็นส่วนตัวและการเก็บข้อมูล', '隐私与数据存储', 'Privacy and data storage'],
  // PDPA notice (owner, 10 Oct 2026): controller, data, purposes and legal basis, recipients, transfers, retention, rights, security
  'pri.sub': ["ประกาศความเป็นส่วนตัวตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA) สำหรับต้นแบบ C.A.L.L. · ปรับปรุง 10 ต.ค. 2569", "C.A.L.L. 原型依据泰国《个人数据保护法》（PDPA，2019年）发布的隐私声明 · 2026年10月10日更新", "Privacy notice for the C.A.L.L. prototype under Thailand's Personal Data Protection Act B.E. 2562 (2019) (PDPA) · updated 10 Oct 2026"],
  'pri.1.h': ["ผู้ควบคุมข้อมูลและช่องทางติดต่อ", "数据控制者与联系方式", "Who is responsible and how to contact us"],
  'pri.1.t': ["ทีมนักศึกษาผู้จัดทำโครงการ C.A.L.L. เป็นผู้ควบคุมข้อมูลส่วนบุคคลของเว็บไซต์นี้ · ติดต่อเรื่องข้อมูลส่วนบุคคลและการใช้สิทธิ: c.a.l.l.project00@gmail.com", "C.A.L.L. 项目学生团队是本网站个人数据的控制者 · 个人数据及行使权利相关事宜请联系：c.a.l.l.project00@gmail.com", "The student team behind the C.A.L.L. project is the data controller of this website · For personal data questions and requests: c.a.l.l.project00@gmail.com"],
  'pri.2.h': ["ข้อมูลที่เก็บ", "收集的数据", "What we collect"],
  'pri.2.t': ["บัญชี: ชื่อ อีเมล ลิงก์รูปโปรไฟล์ (ถ้าเข้าด้วย Google) วันที่สมัครและเข้าระบบล่าสุด · สิ่งที่คุณใส่หรือทำ: บทบาท ชื่อร้าน จังหวัดต้นทาง หมุด ประกาศงาน การสมัครงาน (คำแนะนำตัวและวันที่เริ่มงานได้) ความคืบหน้าของเคส รายงานประกาศที่น่าสงสัย และข้อมูลยืนยันนายจ้าง (เลขทะเบียนนิติบุคคล หรือเบอร์โทรศัพท์เฉพาะ 4 ตัวท้าย) · จำนวนครั้งที่ใช้ AI ในแต่ละวัน · ข้อความที่ส่งให้ AI ตรวจหรือถาม (ส่งต่อไปประมวลผลแต่ไม่บันทึกในฐานข้อมูลของเรา) · ภาษา ธีม และข้อมูลโหมดทดลองเก็บในเบราว์เซอร์ของคุณ · ไม่มีคุกกี้โฆษณาหรือเครื่องมือติดตาม นับเพียงจำนวนการเข้าชมรายวันแบบไม่ระบุตัวบุคคล · รหัสผ่านถูกเข้ารหัสโดยผู้ให้บริการ เราไม่เห็น", "账号：姓名、邮箱、头像链接（使用 Google 登录时）、注册日期和最近登录日期 · 您填写或进行的操作：角色、店铺名、出发省份、标记、招聘信息、求职申请（自我介绍和可入职日期）、个案进度、可疑招聘信息举报，以及雇主验证信息（企业注册号或电话号码后4位）· 每天使用 AI 的次数 · 发送给 AI 检查或提问的文字（会转交处理，但不保存在我们的数据库中）· 语言、主题和体验模式数据保存在您的浏览器中 · 不使用广告 Cookie 或追踪工具，仅以不识别个人的方式统计每日访问次数 · 密码由服务商加密保存，我们看不到", "Account: name, email, profile picture link (if you sign in with Google), sign-up and last sign-in dates · What you enter or do: role, shop name, home province, pins, job posts, applications (introduction and start date), case progress, reports of suspicious posts, and employer verification (company registration number, or only the last 4 digits of a phone number) · How many times a day you use the AI · Text you send for an AI check or question (passed on for processing, not stored in our database) · Language, theme and demo-mode data stay in your browser · No advertising cookies or trackers; only an anonymous daily visit count · Passwords are stored encrypted by the provider; we never see them"],
  'pri.3.h': ["ใช้ทำอะไร และฐานทางกฎหมาย", "用途与法律依据", "Why we use it, and the legal basis"],
  'pri.3.t': ["ให้บริการจับคู่งานตามที่คุณขอใช้ (ฐานสัญญา มาตรา 24(3)) · ดูแลความปลอดภัย ป้องกันงานหลอกลวงและการใช้งานเกินสิทธิ์ เช่น การตรวจรายงานและการจำกัดจำนวนการใช้ AI (ฐานประโยชน์โดยชอบด้วยกฎหมาย มาตรา 24(5)) · นับสถิติรวมเพื่อพัฒนาต้นแบบ · ไม่ขาย ไม่ใช้ทำโฆษณา · ผลจาก AI เป็นเพียงคำแนะนำ การตัดสินใจเป็นของคน", "按您的要求提供工作匹配服务（合同依据，PDPA 第24条第3项）· 维护安全、防范招聘诈骗和超额使用，例如审核举报和限制 AI 使用次数（合法利益依据，第24条第5项）· 统计汇总数据以改进原型 · 不出售数据，不用于广告 · AI 的结果仅供参考，由人作出决定", "To provide the job matching you asked for (contract, PDPA s. 24(3)) · To keep the site safe and stop job scams and overuse, e.g. reviewing reports and limiting AI use (legitimate interests, s. 24(5)) · To count overall statistics to improve the prototype · Never sold or used for advertising · AI results are only advice; people make the decisions"],
  'pri.4.h': ["ใครเห็นข้อมูล", "谁能看到数据", "Who sees your data"],
  'pri.4.t': ["ประกาศงานแสดงต่อผู้หางานที่ตรงเงื่อนไข · นายจ้างเห็นชื่อ คำแนะนำตัว และวันที่เริ่มงานได้ของผู้หางานที่สมัครประกาศของตน (ไม่เห็นอีเมล) · ผู้ดูแลระบบ (ทีมผู้จัดทำ) เห็นข้อมูลที่จำเป็นต่อการดูแลระบบ ตรวจรายงาน และยืนยันนายจ้าง", "招聘信息向符合条件的求职者展示 · 雇主可以看到申请其职位的求职者的姓名、自我介绍和可入职日期（看不到邮箱）· 管理员（项目团队）可以查看维护系统、审核举报和验证雇主所需的数据", "Job posts are shown to job seekers who match them · An employer sees the name, introduction and start date of people who apply to their posts (not their email) · Administrators (the project team) see what they need to run the site, review reports and verify employers"],
  'pri.5.h': ["ผู้ให้บริการที่ประมวลผลแทนเรา", "代表我们处理数据的服务商", "Services that process data for us"],
  'pri.5.t': ["Supabase: ฐานข้อมูลและระบบบัญชี (ศูนย์ข้อมูลสิงคโปร์) · Vercel: โฮสต์เว็บและฟังก์ชันฝั่งเซิร์ฟเวอร์ (สหรัฐอเมริกาและเครือข่ายทั่วโลก) · Google: การเข้าระบบด้วย Google (ถ้าคุณเลือกใช้) และ Gemini API สำหรับฟีเจอร์ AI · ฟีเจอร์ AI ใช้ Gemini แบบไม่เสียค่าใช้จ่าย ซึ่ง Google อาจนำข้อความที่ส่งไปใช้ปรับปรุงบริการและอาจมีคนตรวจอ่าน จึงห้ามใส่ข้อมูลส่วนบุคคลหรือความลับในข้อความที่ให้ AI ตรวจหรือถาม", "Supabase：数据库与账号系统（新加坡数据中心）· Vercel：网站托管与服务器函数（美国及全球网络）· Google：Google 登录（如您选择使用）以及用于 AI 功能的 Gemini API · AI 功能使用免费版 Gemini，Google 可能会使用您发送的文字改进其服务，并可能由人工审阅，因此请勿在发给 AI 的文字中填写个人信息或机密", "Supabase: database and accounts (Singapore data centre) · Vercel: web hosting and server functions (United States and a global network) · Google: Google sign-in (if you choose it) and the Gemini API for the AI features · The AI features use the free Gemini tier, so Google may use the text you send to improve its services and people may read it: never put personal data or secrets in text you send to the AI"],
  'pri.6.h': ["การส่งข้อมูลไปต่างประเทศ", "数据跨境传输", "Transfers outside the country"],
  'pri.6.t': ["ข้อมูลถูกเก็บและประมวลผลนอกประเทศไทย (สิงคโปร์และสหรัฐอเมริกา) โดยผู้ให้บริการข้างต้นภายใต้มาตรการคุ้มครองตามสัญญาของผู้ให้บริการ (PDPA มาตรา 28–29) · ผู้ใช้ในจีน: การสมัครบัญชีและส่งข้อมูลในเว็บนี้ทำให้ข้อมูลถูกส่งออกนอกจีนไปยังประเทศดังกล่าว (กฎหมายคุ้มครองข้อมูลส่วนบุคคลของจีน PIPL มาตรา 38–39) หากไม่ยินยอม โปรดอย่าสมัครบัญชีหรือส่งข้อมูล", "数据由上述服务商在泰国境外（新加坡和美国）存储和处理，并受服务商合同保护措施约束（PDPA 第28–29条）· 中国用户：在本网站注册账号或提交数据，即会将数据传输至中国境外的上述国家（《个人信息保护法》第38–39条）。如不同意，请不要注册账号或提交数据", "Your data is stored and processed outside Thailand (Singapore and the United States) by the services above, under their contractual safeguards (PDPA ss. 28–29) · Users in China: creating an account or submitting data here transfers it out of China to those countries (Personal Information Protection Law, arts. 38–39); if you do not agree, please do not create an account or submit data"],
  'pri.7.h': ["เก็บนานเท่าไร", "保存期限", "How long we keep it"],
  'pri.7.t': ["บัญชีและข้อมูลที่ผูกกับบัญชี: จนกว่าคุณจะลบบัญชี · ประกาศงาน: ลบอัตโนมัติเมื่อครบ 182 วัน (ประมาณ 6 เดือน) หลังเผยแพร่หรือต่ออายุ · หมุด: 30 วัน · บัญชีทดลอง: ลบพร้อมข้อมูลทั้งหมดเมื่อครบ 7 วัน · เมื่อปิดโครงการต้นแบบ ทีมจะลบฐานข้อมูลทั้งหมด", "账号及其关联数据：保存至您删除账号为止 · 招聘信息：发布或续期满182天（约6个月）后自动删除 · 标记：30天 · 体验账号：满7天后连同全部数据一起删除 · 原型项目结束时，团队将删除全部数据库", "Your account and everything linked to it: until you delete the account · Job posts: deleted automatically 182 days (about 6 months) after posting or renewal · Pins: 30 days · Demo accounts: deleted with all their data after 7 days · When the prototype ends, the team deletes the whole database"],
  'pri.8.h': ["สิทธิของคุณ", "您的权利", "Your rights"],
  'pri.8.t': ["ขอเข้าถึงหรือขอสำเนา ขอโอนย้าย คัดค้าน ขอให้ลบ ขอให้ระงับการใช้ ขอให้แก้ไขให้ถูกต้อง และถอนความยินยอม (PDPA หมวด 3) · ลบบัญชีเองได้ทันทีที่ \"โปรไฟล์\" → \"ลบบัญชีของฉัน\" ข้อมูลที่ผูกกับบัญชีจะถูกลบทั้งหมด · เรื่องอื่นส่งอีเมลมาที่ c.a.l.l.project00@gmail.com เราจะตอบภายใน 30 วัน · ร้องเรียนต่อสำนักงานคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล (สคส.) ได้", "您可以要求查阅或获取副本、转移、反对、删除、限制使用、更正数据，以及撤回同意（PDPA 第三章）· 您可以随时在“个人资料”→“删除我的账号”中自行删除账号，关联数据将全部删除 · 其他请求请发送邮件至 c.a.l.l.project00@gmail.com，我们会在30天内答复 · 您也可以向泰国个人数据保护委员会办公室（PDPC）投诉", "Ask to see or get a copy of your data, move it, object, have it deleted, restrict its use, have it corrected, or withdraw consent (PDPA Chapter 3) · Delete your account yourself at any time under \"Profile\" → \"Delete my account\": everything linked to it is removed · For anything else, email c.a.l.l.project00@gmail.com; we reply within 30 days · You may complain to the Personal Data Protection Committee office (PDPC)"],
  'pri.9.h': ["การรักษาความปลอดภัย", "安全措施", "Security"],
  'pri.9.t': ["เชื่อมต่อแบบเข้ารหัส (HTTPS) · ฐานข้อมูลจำกัดสิทธิ์รายแถว (Row Level Security) ให้แต่ละคนเห็นเฉพาะข้อมูลที่มีสิทธิ์ · ไม่เก็บเบอร์โทรเต็มหรือภาพเอกสารยืนยันตัวตน · หากเกิดเหตุข้อมูลรั่วไหลที่มีความเสี่ยง เราจะแจ้ง สคส. ภายใน 72 ชั่วโมง และแจ้งผู้ได้รับผลกระทบ", "加密连接（HTTPS）· 数据库按行限制权限（Row Level Security），每个人只能看到有权查看的数据 · 不保存完整电话号码或身份证件图片 · 如发生有风险的数据泄露，我们会在72小时内通知 PDPC，并通知受影响的用户", "Encrypted connections (HTTPS) · Row Level Security in the database, so each person sees only what they may see · We never store full phone numbers or images of identity documents · If a breach puts people at risk, we tell the PDPC within 72 hours and inform those affected"],
  'pri.10.h': ["ข้อมูลอ่อนไหวและผู้เยาว์", "敏感数据与未成年人", "Sensitive data and minors"],
  'pri.10.t': ["เว็บนี้ไม่ขอข้อมูลอ่อนไหว เช่น ศาสนา สุขภาพ เชื้อชาติ หรือประวัติอาชญากรรม โปรดอย่าใส่ในประกาศหรือคำแนะนำตัว · ผู้ใช้อายุต่ำกว่า 20 ปีควรได้รับความยินยอมจากผู้ปกครองก่อนสมัครบัญชี", "本网站不收集宗教、健康、种族或犯罪记录等敏感数据，请勿在招聘信息或自我介绍中填写 · 未满20岁的用户应在注册前取得监护人同意", "This site does not ask for sensitive data such as religion, health, ethnicity or criminal records — please do not put it in posts or introductions · Users under 20 should get a parent's or guardian's consent before creating an account"],
  'pri.11.h': ["ต้นแบบและการเปลี่ยนแปลง", "原型与变更", "Prototype and changes"],
  'pri.11.t': ["นี่คือต้นแบบสำหรับนำเสนอ ข้อมูลงานและผู้หางานส่วนใหญ่เป็นข้อมูลตัวอย่าง ไม่มีการส่งข้อมูลไปหน่วยงานจริง และไม่มีการรับชำระเงิน อย่ากรอกข้อมูลส่วนบุคคลหรือความลับทางธุรกิจจริง · เมื่อประกาศนี้เปลี่ยน เราจะแก้วันที่ปรับปรุงด้านบน", "这是用于演示的原型。大部分招聘和求职数据为示例，不会发送给任何真实机构，也不收取任何费用。请勿填写真实的个人信息或商业机密 · 本声明如有变更，我们会更新上方的日期", "This is a demonstration prototype. Most job and job-seeker data are samples; nothing is sent to real agencies and no payment is taken. Do not enter real personal data or business secrets · When this notice changes, we update the date above"],
} as const satisfies Record<string, Msg>
